#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'staircase' function below.
#
# The function accepts INTEGER n as parameter.
#

def staircase(n):
    # Write your code here
    for i in range(n):
        a = (i + 1) * '#'
        b = (n - (i+2)) * ' '
        if i == n-1:
            print (a)
        else:
            print (b, a)

if __name__ == '__main__':
    n = int(input().strip())

    staircase(n)
